#pragma warning disable SA1202 // 'public' members should come before 'private' members
#pragma warning disable SA1203 // Constant fields should appear before non-constant fields
namespace Yash;

public static class Constants
{
    // Namespaces
    public const string Namespace = "Yash.Generated";
    public const string AttributeNamespace = $"{Namespace}.Attributes";

    // Attributes
    public const string AttributeName = "YashAttribute";
    public const string AttributeFullName = $"{AttributeNamespace}.{AttributeName}";

    // Misc code generation
    public static readonly string GeneratedCodeAttribute =
        $@"[global::System.CodeDom.Compiler.GeneratedCodeAttribute(""{typeof(Constants).Assembly.GetName().Name}"", ""{typeof(Constants).Assembly.GetName().Version}"")]";

    public const string GeneratedComment = "// <auto-generated />";
    public const string EnableNullable = "#nullable enable";
    public const string FileHintSuffix = "g.cs";
    public const string BaseClassNameSuffix = "Base";
    public const string DefaultValuesTypeName = "DefaultValuesRecord";
    public const string DefaultValuesPropertyName = "DefaultValues";
    public const string InternalPropertySuffix = "Internal";
    public const string InternalBuildMethodName = "BuildInternal";

    // Misc Analyzer
    public const string DiagnosticPrefix = "YASH";

    // DiagnosticIds
    public const string YashClassNeedsToBePartialDiagnosticId = $"{DiagnosticPrefix}0001";
    public const string YashClassCantBeStaticDiagnosticId = $"{DiagnosticPrefix}0002";
    public const string YashClassWithMissingInternalBuildMethodDiagnosticId = $"{DiagnosticPrefix}0003";
    public const string YashClassMultipleInternalBuildMethodsDiagnosticId = $"{DiagnosticPrefix}0004";
}