name: TestPackPublish
on:
    release:
        types:
            - published

env:
    NuGetDirectory: ${{ github.workspace}}/nuget

jobs:
    test:
        if: github.event_name == 'release'
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Setup .NET
                uses: actions/setup-dotnet@v3
            -   name: Run tests
                run: dotnet test --configuration Release

    pack:
        if: github.event_name == 'release'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup .NET
              uses: actions/setup-dotnet@v3
            - run: dotnet pack --configuration Release --output ${{ env.NuGetDirectory }} -p:Version="${{github.ref_name}}"
            - uses: actions/upload-artifact@v3
              with:
                  name: nuget
                  if-no-files-found: error
                  retention-days: 7
                  path: ${{ env.NuGetDirectory }}/*.nupkg

    publish:
        if: github.event_name == 'release'
        runs-on: ubuntu-latest
        needs: [ test, pack ]
        steps:
            - uses: actions/download-artifact@v3
              with:
                  name: nuget
                  path: ${{ env.NuGetDirectory }}
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
            - name: Publish NuGet package
              run: dotnet nuget push ${{ env.NuGetDirectory }}/*.nupkg --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate